baseurl = "http://www.pingouindoc.tuxfamily.org/hugo/"
languageCode = "fr-fr"
title = "Pinguin Web Banqu'is Master"
theme = "blackburn"
author = "Patrice Blondel"
email = "govez@pingouindesalpes.com"
copyright = "&copy; 2017.     <br />Tous droits réservés."
canonifyurls = true
paginate = 10
[taxonomies]
    # Optional. Use if you want tags and lists.
    category = "categories"
    tag = "tags"
    topic = "topics"

[indexes]
  tag = "tags"
  topic = "topics"

[params]
  # Shown in the home page
  subtitle = "Aide-mémoire pour webmaster"
  brand = "Le pingouin <br />  des @lpes"
  googleAnalytics = "Your Google Analytics tracking ID"
  disqus = "Your Disqus shortname"
  # CSS name for highlight.js
  highlightjs = "androidstudio"
  dateFormat = "02 Jan 2006, 15:04"
  locale = "fr-FR"
  
[menu]
  # Shown in the side menu.
  [[menu.main]]
    name = "Accueil"
    pre = "<i class='fa fa-home fa-fw'></i>"
    weight = 0
    identifier = "home"
    url = "/"
  [[menu.main]]
    name = "Articles"
    pre = "<i class='fa fa-list fa-fw'></i>"
    weight = 1
    identifier = "post"
    url = "/post/"

  [[menu.main]]
    name = "Memento"
    pre = "<i class='fa fa-info-circle fa-fw'></i>"
    weight = 2
    identifier = "memento"
    url = "/memento/"

   [[menu.main]]
    name = "Catégories"
    pre = "<i class='fa fa-book fa-fw'></i>"
    weight = 3
    identifier = "topics"
    url = "/topics/"

   [[menu.main]]
    name = "Tags"
    pre = "<i class='fa fa-tag fa-fw'></i>"
    weight = 4
    identifier = "tags"
    url = "/tags/"
   
   [[menu.main]]
    name = "À propos"
    pre = "<i class='fa fa-user fa-fw'></i>"
    weight = 5
    identifier = "about"
    url = "/about/"



[social]
  # Link your social networking accouns to the side menu
  # by entering your username or ID.
  #twitter = "*"
  facebook = "patrice.blondel"
  #instagram = "*"
  github = "govez"
  #stackoverflow = "*"
  #linkedin = "*"